#!/bin/sh
lb config noauto \
    --mirror-binary http://ftp.fr.debian.org/debian/ \
    --mirror-chroot http://ftp.fr.debian.org/debian/ \
    --mirror-bootstrap http://ftp.fr.debian.org/debian/ \
    --mirror-binary-security http://security.eu.debian.org/ \
    --mirror-chroot-security http://security.eu.debian.org \
    --apt apt \
    --bootloader grub \
    --linux-flavours 486 \
    --hooks minimal \
    --memtest none \
    --iso-application "Dlive Airo" \
    --iso-publisher "David Francos (XayOn) <me@davidfrancos.net>" \
    --iso-volume "Dlive Airo" \
    --apt-secure "false" \
    --apt-recommends disabled \
    --package-lists "dlive" \
    --distribution sid \
    --architecture i386 \
    --archive-areas "main contrib non-free" \
    --system live \
    --clean \
    -b iso \
    "${@}"


#    --clean \
